/*
 * Minerva - Game, Copyright 2010 Christian Bollmann, Carina Strempel, André König
 * Hochschule Bremen - University of Applied Sciences - All Rights Reserved.
 *
 * $Id: ColorTool.java 656 2010-07-04 16:11:39Z andre.koenig $
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Contact:
 *     Christian Bollmann: cbollmann@stud.hs-bremen.de
 *     Carina Strempel: cstrempel@stud.hs-bremen.de
 *     André König: akoenig@stud.hs-bremen.de
 * 
 * Web:
 *     http://minerva.idira.de
 * 
 */
package de.hochschule.bremen.minerva.commons.util;

import java.awt.Color;

/**
 * Some color tools ;)
 * Converting color to hexcodes for example.
 *
 * @since 1.0
 * @version $Id: ColorTool.java 656 2010-07-04 16:11:39Z andre.koenig $
 * 
 */
public class ColorTool {

	/**
	 * Converting a given color to the hex color
	 * description
	 * 
	 * @param color The color we would like to convert.
	 * @return A String like 'ffffff'
	 * 
	 */
	public static String toHexCode(Color color) {
		return String.format("%02X%02X%02X", color.getRed(), color.getGreen(), color.getBlue()).toLowerCase();
	}

	/**
	 * Converts a string with an hexa coded color
	 * to a java.awt.Color
	 * 
	 * @param hexa A String like 'ff0000'
	 * @return The @see java.awt.Color generated by the given hexa.
	 * 
	 */
	public static Color fromHexCode(String hexa) {
		if (!hexa.startsWith("#")) {
			hexa = "#"+hexa;
		}
		return Color.decode(hexa);
	}

	/**
	 * Creates a color object from an rgb integer value.
	 * 
	 * @param rgb
	 * @return The @see java.awt.Color generated by the given integer.
	 * 
	 */
	public static Color fromInteger(int rgb) {
		return new Color(rgb);
	}
}
